# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: app
          image: lemi101/ping-pong:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong
spec:
  selector:
    app: ping-pong
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---